#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/PL2

PRODUCT_COPY_FILES += \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2592x1944.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_3264x2448.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_864x480.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2592x1944.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_3264x2448.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_864x480.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_3200x2400.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_3840x2160.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_4608x3456.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_3200x2400.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_3840x2160.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_4608x3456.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Bluetooth_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/General_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Global_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Handset_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Hdmi_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Headset_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Speaker_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/audio_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/camera/calibration_test.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calibration_test.bin \
    vendor/nokia/PL2/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/camera/s5k3p3_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3_chromatix.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/camera/s5k4h8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h8_chromatix.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/camera/s5k4h8_pl2_holitech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h8_pl2_holitech_chromatix.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/nokia/PL2/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/nfcee_access.xml:$(TARGET_COPY_OUT_VENDOR)/etc/nfcee_access.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/nokia/PL2/proprietary/vendor/etc/sec_s3nrn81_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_s3nrn81_rfreg.bin \
    vendor/nokia/PL2/proprietary/vendor/etc/sensors/sensor_def_qcomdev_pl2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev_pl2.conf \
    vendor/nokia/PL2/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nokia/PL2/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/nokia/PL2/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/nokia/PL2/proprietary/vendor/etc/wifi/bdf/bdwlan_PL2_cal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_PL2_cal.bin \
    vendor/nokia/PL2/proprietary/vendor/etc/wifi/bdf/bdwlan_def.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_def.bin \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891M04.drc:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891M04.drc \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891M04.vstep:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891M04.vstep \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891R04.drc:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891R04.drc \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891R04.vstep:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891R04.vstep \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891S04.drc:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891S04.drc \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891S04.vstep:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891S04.vstep \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891V04.drc:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891V04.drc \
    vendor/nokia/PL2/proprietary/vendor/firmware/T9891V04.vstep:$(TARGET_COPY_OUT_VENDOR)/firmware/T9891V04.vstep \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891.cnt \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891.cnt_preformat.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891.cnt_preformat.ini \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891.ini \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891.speaker:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891.speaker \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891N1A_Dec2015.config:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891N1A_Dec2015.config \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891_N1A_11_1_31_NL3_HQ.patch:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891_N1A_11_1_31_NL3_HQ.patch \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891_pl2.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891_pl2.cnt \
    vendor/nokia/PL2/proprietary/vendor/firmware/TFA9891_pl2.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/TFA9891_pl2.ini \
    vendor/nokia/PL2/proprietary/vendor/firmware/TP_Firmware_FT8716_PL2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TP_Firmware_FT8716_PL2.bin \
    vendor/nokia/PL2/proprietary/vendor/firmware/a508_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.b01 \
    vendor/nokia/PL2/proprietary/vendor/firmware/a508_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.mdt \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b00 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b02 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b03 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b04 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b05 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b06 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b00 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b02 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b03 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b04 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b05 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cmnlib64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b06 \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b00 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b01 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b02 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b03 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b04 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b05 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b06 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.b07 \
    vendor/nokia/PL2/proprietary/vendor/firmware/elanfp64.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/elanfp64.mdt \
    vendor/nokia/PL2/proprietary/vendor/firmware/sec_s3nrn81_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_firmware.bin \
    vendor/nokia/PL2/proprietary/vendor/usr/keylayout/elan.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/elan.kl

PRODUCT_PACKAGES += \
    libsensor1 \
    libsensor_reg \
    sensor_calibrate \
    sensors.ssc \
    camera.sdm660 \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_dw9800 \
    libactuator_pseudo \
    libadiertac \
    libadm \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libaoa \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_night_shot \
    libarcsoft_picselfie_algorithm \
    libarcsoft_smart_denoise \
    libaudcal \
    libaudioalsa \
    libchromatix_s5k3p3_common \
    libchromatix_s5k3p3_cpp_hfr_120 \
    libchromatix_s5k3p3_cpp_hfr_60 \
    libchromatix_s5k3p3_cpp_hfr_90 \
    libchromatix_s5k3p3_cpp_liveshot \
    libchromatix_s5k3p3_cpp_preview \
    libchromatix_s5k3p3_cpp_snapshot \
    libchromatix_s5k3p3_cpp_video \
    libchromatix_s5k3p3_default_preview_dw9800 \
    libchromatix_s5k3p3_default_video \
    libchromatix_s5k3p3_default_video_dw9800 \
    libchromatix_s5k3p3_hfr_120 \
    libchromatix_s5k3p3_hfr_120_dw9800 \
    libchromatix_s5k3p3_hfr_60 \
    libchromatix_s5k3p3_hfr_60_dw9800 \
    libchromatix_s5k3p3_hfr_90 \
    libchromatix_s5k3p3_hfr_90_dw9800 \
    libchromatix_s5k3p3_postproc \
    libchromatix_s5k3p3_preview \
    libchromatix_s5k3p3_snapshot \
    libchromatix_s5k3p3_snapshot_longexposure \
    libchromatix_s5k3p3_versions \
    libchromatix_s5k3p3_zsl_preview_dw9800 \
    libchromatix_s5k3p3_zsl_video_dw9800 \
    libchromatix_s5k4h8_a3_default_preview \
    libchromatix_s5k4h8_a3_default_video \
    libchromatix_s5k4h8_a3_hfr_120 \
    libchromatix_s5k4h8_a3_hfr_60 \
    libchromatix_s5k4h8_a3_hfr_90 \
    libchromatix_s5k4h8_common \
    libchromatix_s5k4h8_cpp_hfr_120 \
    libchromatix_s5k4h8_cpp_hfr_60 \
    libchromatix_s5k4h8_cpp_hfr_90 \
    libchromatix_s5k4h8_cpp_liveshot \
    libchromatix_s5k4h8_cpp_preview \
    libchromatix_s5k4h8_cpp_snapshot \
    libchromatix_s5k4h8_cpp_video \
    libchromatix_s5k4h8_default_video \
    libchromatix_s5k4h8_hfr_120 \
    libchromatix_s5k4h8_hfr_60 \
    libchromatix_s5k4h8_hfr_90 \
    libchromatix_s5k4h8_liveshot \
    libchromatix_s5k4h8_pl2_holitech_a3_default_preview \
    libchromatix_s5k4h8_pl2_holitech_a3_default_video \
    libchromatix_s5k4h8_pl2_holitech_a3_hfr_120 \
    libchromatix_s5k4h8_pl2_holitech_a3_hfr_60 \
    libchromatix_s5k4h8_pl2_holitech_a3_hfr_90 \
    libchromatix_s5k4h8_pl2_holitech_common \
    libchromatix_s5k4h8_pl2_holitech_cpp_hfr_120 \
    libchromatix_s5k4h8_pl2_holitech_cpp_hfr_60 \
    libchromatix_s5k4h8_pl2_holitech_cpp_hfr_90 \
    libchromatix_s5k4h8_pl2_holitech_cpp_liveshot \
    libchromatix_s5k4h8_pl2_holitech_cpp_preview \
    libchromatix_s5k4h8_pl2_holitech_cpp_snapshot \
    libchromatix_s5k4h8_pl2_holitech_cpp_video \
    libchromatix_s5k4h8_pl2_holitech_default_video \
    libchromatix_s5k4h8_pl2_holitech_hfr_120 \
    libchromatix_s5k4h8_pl2_holitech_hfr_60 \
    libchromatix_s5k4h8_pl2_holitech_hfr_90 \
    libchromatix_s5k4h8_pl2_holitech_liveshot \
    libchromatix_s5k4h8_pl2_holitech_postproc \
    libchromatix_s5k4h8_pl2_holitech_preview \
    libchromatix_s5k4h8_pl2_holitech_snapshot \
    libchromatix_s5k4h8_pl2_holitech_versions \
    libchromatix_s5k4h8_pl2_holitech_zsl_preview \
    libchromatix_s5k4h8_pl2_holitech_zsl_video \
    libchromatix_s5k4h8_postproc \
    libchromatix_s5k4h8_preview \
    libchromatix_s5k4h8_snapshot \
    libchromatix_s5k4h8_versions \
    libchromatix_s5k4h8_zsl_preview \
    libchromatix_s5k4h8_zsl_video \
    libdepthmapwrapper \
    libfih_camera_effect \
    libflash_dummy_flash \
    libflash_pmic \
    libhal_dbg \
    libimage_matting \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3p3 \
    libmmcamera_s5k3p3_m24c64s_eeprom \
    libmmcamera_s5k4h8 \
    libmmcamera_s5k4h8_eeprom \
    libmmcamera_s5k4h8_holitech_eeprom \
    libmmcamera_s5k4h8_pl2_holitech \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libpn553_fw \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    android.hardware.keymaster@3.0-impl-qti \
    fingerprint.elan \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_800h_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    cnss-daemon \
    android.hardware.keymaster@3.0-service-qti \
    mm-qcamera-app \
    sensors.qti
